### ISSUE TITLE
Bottom log HAS to be broken first in order to treeassist to work

### ISSUE THREAD

**Issue by NathanCollaert** [slipcor/TreeAssist#30] opened 2019-06-01 10:52 UTC
Even tho my config file looks like this: https://pastebin.com/kZ94d5Jx
And the option for bottom log has to be broken first is set to false, TreeAssist still requires the bottom log to be broken for it to work.
I'm using the latest version of TreeAssist and it worked like intended and stopped working but the weird part is that this happened mid season of 1.13.2 without touching the plugin.

**Comment by slipcor** [comment] 2019-06-01 12:11
Sounds like Spigot changed something then? I will try to reproduce this.

Also it seems that the config is not really like I remember it. There is no setting for the **auto destruct** to require bottom block, I only see a setting for the **sapling replace** to require that.

When I cannot reproduce this I might need your help with a debug on your end. Stay tuned!

**Comment by NathanCollaert** [comment] 2019-06-01 12:27
I noticed that too and I've talked to pop about it as well but he couldn't reproduce it.
If you need any info, please contact me on Discord as it's a bit easier to talk: Nathan#4444

**Comment by slipcor** [comment] 2019-06-02 14:37
fixed in version 65

**Closed by slipcor** 2019-06-02 14:37 UTC
Labels: bug
